#!/bin/sh
# prerm script for APPLICATION_PACKAGE
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <prerm> `remove'
#        * <old-prerm> `upgrade' <new-version>
#        * <new-prerm> `failed-upgrade' <old-version>
#        * <conflictor's-prerm> `remove' `in-favour' <package> <new-version>
#        * <deconfigured's-prerm> `deconfigure' `in-favour'
#          <package-being-installed> <version> `removing'
#          <conflicting-package> <version>
# for details, see https://www.debian.org/doc/debian-policy/ or
# the debian-policy package


# shellcheck disable=SC2034 # read by the code jpackage puts in place of the placeholders
package_type=deb
COMMON_SCRIPTS
DESKTOP_SCRIPTS
LAUNCHER_AS_SERVICE_SCRIPTS

case "$1" in
    remove|upgrade|deconfigure)
        # The one change to what jpackage's own template does, as in postinst: with no
        # desktop, the menu tool fails, and that must not stop the package being removed.
        set +e
DESKTOP_COMMANDS_UNINSTALL
        set -e
LAUNCHER_AS_SERVICE_COMMANDS_UNINSTALL
    ;;

    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
